Add more webistes [Update data.json]
deamme/usecrypto pull request #3
Opened 2019-10-09 21:25 UTC by DjamelEd

2019-10-09 21:38 UTC, FrederikBolding commented
Thanks! That looks better! Will get to looking at it soon!

2019-10-09 21:45 UTC, deamme commented
You can accept BTC as a merchant right? But shopify itself doesn't accept BTC payments in any form. What could be nice to add is the merchants themselves that accepts BTC.

For example those listed here: https://www.shopify.com/bitcoin

2019-10-10 07:12 UTC, deamme commented on data/data.json
> +    "link": "https://www.enclavemfg.com//",
Typo here `//`

2019-10-10 07:56 UTC, deamme commented
I modified the `data.json` a bit so now we have conflicting changes. Can you please resolve them? Sorry about that.

2019-10-10 08:28 UTC, deamme commented
@DjamelEd `category` is renamed to `categories` which takes an array now. Can you resolve this too?

2019-10-10 09:05 UTC, FrederikBolding requested changes

2019-10-10 09:05 UTC, FrederikBolding commented on data/data.json
> +    "categories": [],
Please add a category here! 😄

2019-10-10 10:02 UTC, merged